name: remote ssh command
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          set -x  # Enable debug mode
          mkdir ~/.ssh || { echo "Failed to create .ssh directory"; exit 1; }
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa || { echo "Failed to write id_rsa"; exit 1; }
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub || { echo "Failed to write id_rsa.pub"; exit 1; }
          chmod 600 ~/.ssh/id_rsa || { echo "Failed to set permissions on id_rsa"; exit 1; }
          chmod 600 ~/.ssh/id_rsa.pub || { echo "Failed to set permissions on id_rsa.pub"; exit 1; }
          echo "Connecting to ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }}"
          ping -c 4 ${{ secrets.HOST }} || { echo "Failed to reach host"; exit 1; }
          ssh-keyscan -H 185.229.114.148 >> ~/.ssh/known_hosts || { echo "Failed to add host to known_hosts"; exit 1; }
          chmod 644 ~/.ssh/known_hosts || { echo "Failed to set permissions on known_hosts"; exit 1; }
        env:
          USERNAME: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          HOST: ${{ secrets.HOST }}

      - name: SSH and Git pull
        run: |
          ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd ~/domains/iceithq.com/public_html/test && git pull origin main" || { echo "SSH command failed"; exit 1; }
        env:
          USERNAME: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
